baseURL = "https://oakbear.github.io/"

theme = "LoveIt"


languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = true


#这是标签页名称
title = "致亘古不变之物"



[markup]
  [markup.highlight]
    noClasses = false




#以下五行无效
[params]
  # 网站在 Open Graph / SEO / 头部显示的标题／描述
  title = "致"
  description = "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
  name = "d"

#这是左上角
[params.header.title]
  title = "致"
  description = "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
  name = "K"

# config.toml for time
enableGitInfo = true




[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "文章"
    url = "/posts/"

  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "标签"
    url = "/tags/"

  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "分类"
    url = "/categories/"

  [[menu.main]]
    weight = 4
    identifier = "about"
    name = "关于"
    url = "/about/"
    
  [[menu.main]]
      name = "Games"
      url = "/games/"
      weight = 5



[params.home.profile]
title = "Echo"
subtitle = "just as it has always been"
name = "dundme" #无效
